apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: actions-exporter
  namespace: github-actions-exporter
spec:
  backendType: secretsManager
  data:
 # for personal access token authentication 
 #   - key: MYSECRETMANAGERKEY
 #     name: github_token
 #     property: token
 # for github app authentication
    - key: MYSECRETMANAGERKEY
      name: github_app_id
      property: github_app_id
    - key: MYSECRETMANAGERKEY
      name: github_app_installation_id
      property: github_app_installation_id
  # separate plaintext aws secret needed for ssh key
    - key: MYSECRETMANAGERKEY_github_app_private_key
      name: github_app_private_key
