apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 30m
  url: https://neillturner.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  chart:
    spec:
      chart: actions-runner-controller
      version: "0.12.0"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: actions-runner-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    authSecret:
      create: false
    metrics:
      serviceMonitor: false
      port: 8080
      proxy:
        enabled: false  
    scope:
      singleNamespace: true
      watchNamespace: "github-actions"