apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-runner
  namespace: github-actions
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::09999999999:role/github-actions-runner
